#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define ROOT_NODE 0
#define DEFAULT_TAG 0

#define RECEIVE_BUFFER_SIZE 100000

#define INVALID_FITNESS_VALUE INT_MAX

#define LOCAL_POPULATION_SIZE 58
#define LOCAL_OPTIMIZATION_EPOCHES 1000000

#define CHROMOSOMES_INITIAL_SIZE 1

#define CUBE_SHUFFLING_STEPS 10000

#define NUMBER_OF_BROADCASTS 67

#define COMMANDS_REDUCTION true

#define RANDOM_TRAVELER true

#endif
